/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ocr_one_MainActivity */

#ifndef _Included_com_example_ocr_one_MainActivity
#define _Included_com_example_ocr_one_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ocr_one_MainActivity
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_ocr_1one_MainActivity_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
